# Gradeint Descent

- 머신러닝의 가장 기본이 되는 경사하강법을 실습해보자
- greedy하게 찾아가는 방법이므로 손실함수(비용함수)를 잘 설정해야 함(convex하게)
- 절차:
    1. 초기 parameter를 설정함
    2. 답과 초기 param값으로 계산한 예측값을 비교
    3. 적절히 설정한 손실함수에 기초해서 param update
    4. 적정 수준까지 반복
  
    
- 규제 모형들의 경우 비용함수에 적절히 규제항을 추가하여 대부분 구성함

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

d = load_boston()

In [2]:
d.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [3]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
data = pd.DataFrame(std.fit_transform(d.data), columns=d.feature_names)
target = std.fit_transform(d.target.reshape(-1,1))

In [4]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(data, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
lr.coef_

array([[-0.10101708,  0.1177152 ,  0.0153352 ,  0.07419883, -0.22384803,
         0.29105647,  0.00211864, -0.33783635,  0.28974905, -0.22603168,
        -0.22427123,  0.09243223, -0.40744693]])

In [6]:
dd = data.iloc[:,0:3]
lr = LinearRegression().fit(dd, target)
lr.coef_

array([[-0.23252837,  0.14834915, -0.30999003]])

In [7]:
def update(w, X, y, lr=0.001):
    X['int'] = np.ones(len(X))
    f = (X.T@X @ w).values
    b = X.T@y
    bb = list(list(zip(*b.values))[0])
    bb = (np.multiply(-1, bb))
    w_update = np.add(f, bb)
    w = np.add(w, np.multiply(-1*lr, w_update))
    y_pred = pd.DataFrame((X @ w).T)
    diff = y - y_pred
    print(np.sum(np.square(y-y_pred))[0])
    return w, np.sum(np.square(y-y_pred))[0]

In [8]:
w = [-0.1, 0.3, -0.1, 0]
update(w, dd, target)

367.2336968415681


c:\users\young\anaconda3\envs\study\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


(array([-1.94877784e-01,  2.93429895e-01, -1.92556692e-01, -3.36841666e-16]),
 367.2336968415681)

In [9]:
e = 10000
for _ in range(1000):
    w, error = update(w, dd, target)
    if error > e:
        break
    else:
        e = error

c:\users\young\anaconda3\envs\study\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


367.2336968415681
362.245178274099
359.99252012054023
358.86250141461835
358.2535211913927
357.90717602281734
357.70285924942976
357.57951629717445
357.50401748151785
357.4574294687678
357.4285480106026
357.41059632600115
357.3994216424351
357.3924597477676
357.38812041442617
357.38541500727524
357.38372804182313
357.38267604223125
357.38201998001375
357.3816108270237
357.3813556551921
357.3811965137602
357.38109726255965
357.3810353627401
357.3809967577346
357.38097268096595
357.38095766501027
357.3809483000085
357.38094245933667
357.38093881668374
357.38093654486966
357.3809351280068
357.38093424435164
357.3809336932422
357.3809333495317
357.38093313516964
357.3809330014784
357.3809329180992
357.38093286609796
357.3809328336664
357.3809328134398
357.3809328008251
357.38093279295765
357.380932788051
357.3809327849909
357.38093278308236
357.380932781892
357.3809327811496
357.3809327806867
357.3809327803979
357.38093278021785
357.3809327801055
357.38093278003555
357.3809327799918
357.38

In [10]:
w

array([-2.32528370e-01,  1.48349151e-01, -3.09990023e-01, -1.35546899e-15])

In [11]:
lr.coef_

array([[-0.23252837,  0.14834915, -0.30999003]])