1. gradient descent normal
2. gradient descent l2(ratio = 1)
3. sklearn logistic(penalty == 'none')
4. sklearn logistic(penalty == 'l2')
5. NN

** sklearn에서 어떤 트릭을 써서 성능을 향상시키는지는 불확실함  
** logistic에서 loss는 binary_crossentropy

In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

d = load_breast_cancer()

data = pd.DataFrame(d.data, columns=d.feature_names)
target = pd.DataFrame(d.target)

train_X, test_X, train_y, test_y = train_test_split(data, target, test_size=0.3, random_state=2019, shuffle=True)

In [2]:
d = (train_X - np.mean(train_X))/np.std(train_X)
data = d.copy()
test_X = (test_X - np.mean(test_X)) / np.std(test_X)
t = test_X.copy()

In [3]:
d['const'] = np.ones_like(d['mean area'])
t['const'] = np.ones_like(test_X['mean area'])

In [4]:
d

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
14     -0.116417      0.790962        0.063844  -0.220533         1.254004   
514     0.256038     -0.052228        0.213188   0.128310        -0.271490   
537    -0.692029      1.226849       -0.639215  -0.705696         2.018572   
331    -0.328039      0.014465       -0.306659  -0.402010        -0.006440   
79     -0.361899     -0.307091       -0.360929  -0.423742         0.252057   
..           ...           ...             ...        ...              ...   
24      0.707499      0.497989        0.733036   0.700401         1.181188   
190     0.021843      0.912439        0.095264  -0.131347         0.846235   
159    -0.914938     -1.507565       -0.952592  -0.817461        -1.509362   
370     0.622850      0.952931        0.692232   0.519206         0.112250   
72      0.862688      1.245904        0.904415   0.770396         0.817109   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
14           2.389836        1.598685             0.796560       0.911954   
514         -0.313884       -0.148491            -0.130305      -0.882069   
537          0.992043       -0.524804            -0.081073       1.130910   
331          0.186568       -0.196496            -0.478193      -0.175761   
79          -0.134868       -0.604094            -0.637694      -0.327617   
..                ...             ...                  ...            ...   
24           0.812839        0.834913             1.084165       0.650620   
190          2.616200        1.412492             0.443146       2.024390   
159         -1.234239       -1.057544            -1.053703      -1.302323   
370          0.888294        1.197167             0.984445       1.286298   
72           1.516452        1.046439             0.776214       0.410475   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
14                 2.165735  ...       1.053857         0.049098   -0.319986   
514               -0.513503  ...       0.392530         0.197541    0.153593   
537                1.745730  ...       1.083993        -0.624240   -0.689282   
331                0.434162  ...      -0.630433        -0.235616   -0.431478   
79                -0.389169  ...      -0.149925        -0.453234   -0.452932   
..                      ...  ...            ...              ...         ...   
24                 0.115747  ...       0.978516         2.073864    2.348271   
190                1.953458  ...       1.919441        -0.022155   -0.206207   
159               -0.774300  ...      -1.258275        -0.863234   -0.720409   
370               -0.054075  ...       0.889781         0.657715    0.501787   
72                 0.353800  ...       1.356895         1.319772    1.409202   

     worst smoothness  worst compactness  worst concavity  \
14           1.435091           3.430777         2.183769   
514         -0.320347          -0.253977         0.116111   
537          1.942218           0.499485        -0.629909   
331         -0.138302           0.500795         0.406709   
79          -0.133967          -0.227769        -0.459506   
..                ...                ...              ...   
24           2.102591           0.713730         1.043692   
190          0.923630           4.480381         2.967318   
159         -0.645428          -1.087108        -1.243360   
370          0.412169           1.425914         2.256799   
72           1.149020           3.213911         1.992573   

     worst concave points  worst symmetry  worst fractal dimension  const  
14               1.612591        1.088157                 3.580816    1.0  
514             -0.029137       -0.981803                -0.809866    1.0  
537              0.254544       -0.161066                 0.990338    1.0  
331             -0.231637        1.088157                 0.510443    1.0  
79              -0.523165       -0.198873                -0.234469   

In [5]:
def logit(x, y, p=False, lr=0.01):
#     if not p:
#         p = np.random.normal(0, 1, len(x[0]))
    t = np.array(list(map(lambda x: 1/(1 + np.exp(-x)), x@p))) - y.flatten()
    
    res = t.T @ x
    return p - np.dot(res, lr/len(x)), np.sum(res)/len(x)


In [6]:
np.random.seed(0)
p1 = np.random.normal(0, 0.1, len(d.values[0]))
# p = np.zeros_like(d.columns)
for _ in range(200):
    p1, j = logit(d.values, train_y.values, p1, lr=0.01)
    print(_, '######')
    print(j)
    print(p1)
    if j < 0:
        break

0 ######
9.7033109214502
[ 1.72000555e-01  3.73490084e-02  9.33527556e-02  2.19755691e-01
  1.83519319e-01 -1.02051500e-01  9.01368826e-02 -2.02116727e-02
 -1.30031879e-02  4.01907470e-02  1.07412049e-02  1.45160177e-01
  7.24841881e-02  8.54732662e-03  4.42489751e-02  3.08076620e-02
  1.46653421e-01 -2.36592387e-02  3.08249057e-02 -8.68970346e-02
 -2.59967978e-01  6.24225202e-02  8.16798988e-02 -7.86909951e-02
  2.23701407e-01 -1.49545568e-01 -6.04919585e-05 -2.38352073e-02
  1.50294486e-01  1.44270428e-01  1.68122900e-02]
1 ######
9.453288367800083
[ 0.16771154  0.03474101  0.08895061  0.21553575  0.18035363 -0.10625725
  0.08539089 -0.02515734 -0.01562033  0.03934616  0.00717189  0.14488764
  0.06895942  0.00502147  0.04410198  0.02832822  0.14398188 -0.02670822
  0.03034588 -0.08833254 -0.26451426  0.05954425  0.0770422  -0.08304614
  0.22049232 -0.1535439  -0.00457633 -0.02881964  0.14737467  0.14167584
  0.01811682]
2 ######
9.198542987152507
[ 0.16353966  0.03219233  0.08466898 

108 ######
1.3116324396211378
[-0.00320719 -0.08387246 -0.08428109  0.04932099  0.05613191 -0.24336243
 -0.08852454 -0.21459378 -0.10877627  0.03469421 -0.13056068  0.13239537
 -0.0598136  -0.12681341  0.03853892 -0.02398793  0.07821592 -0.116396
  0.02193156 -0.1028298  -0.45007677 -0.07880762 -0.10850854 -0.25759713
  0.07394787 -0.295302   -0.1753285  -0.22453996  0.01867224  0.05282858
  0.12091524]
109 ######
1.3003281113660796
[-0.00397561 -0.08444953 -0.08504565  0.04857298  0.05566058 -0.24374886
 -0.08919581 -0.21537677 -0.1090786   0.03489355 -0.13119634  0.13235119
 -0.06036756 -0.12739963  0.03853428 -0.02391625  0.07817991 -0.11658672
  0.02196224 -0.10260887 -0.45093827 -0.07951556 -0.10934847 -0.2584035
  0.07326861 -0.29577344 -0.17599325 -0.22535202  0.01808235  0.05258305
  0.12159182]
110 ######
1.2892140140132833
[-0.00473875 -0.08502299 -0.08580483  0.04782999  0.05519359 -0.24413031
 -0.08986159 -0.21615375 -0.10937761  0.03509368 -0.13182833  0.13230733
 -0.06091

In [7]:
def logit_l2(x, y, p=False, lr=0.001, l2=3):
#     if not p:
#         p = np.random.normal(0, 1, len(x[0]))
    t = np.array(list(map(lambda x: 1/(1 + np.exp(-x)), x@p))) - y.flatten()
    
    res = (t.T @ x) / len(x)
    return p - np.dot(res+2*l2*p, lr), np.sum(res)/len(x)


In [8]:
np.random.seed(0)
p2 = np.random.normal(0, 0.1, len(d.values[0]))
# p = np.zeros_like(d.columns)
for _ in range(100):
    p2, j = logit_l2(d.values, train_y.values, p2, lr=0.01)
    print(_, '######')
    print(j)
    print(p2)
#     if j < 0:
#         break


0 ######
0.024380178194598492
[ 0.16141624  0.03494807  0.08748033  0.20631033  0.17231397 -0.09618783
  0.08443635 -0.01930353 -0.01238387  0.03772716  0.00987694  0.13643454
  0.06791796  0.00781728  0.0415858   0.02880562  0.13768895 -0.02242829
  0.0289465  -0.08177246 -0.24465004  0.05850081  0.07649328 -0.074238
  0.21008288 -0.14081937 -0.00033504 -0.0227121   0.14109781  0.13545428
  0.01588261]
1 ######
0.023397138101678247
[ 0.14748493  0.03028049  0.07787475  0.1897557   0.15887311 -0.09455717
  0.07469022 -0.02302628 -0.0142101   0.03465628  0.00576008  0.12799763
  0.06036384  0.00386478  0.03896959  0.02464247  0.12680274 -0.02408311
  0.02675038 -0.07826365 -0.23447031  0.05215516  0.06731539 -0.07409208
  0.19433082 -0.13631136 -0.00476872 -0.02627061  0.12975615  0.12478145
  0.01623073]
2 ######
0.022430915868720803
[ 0.13454377  0.02598621  0.0690058   0.17434867  0.14637191 -0.0928444
  0.06571783 -0.02633442 -0.01581585  0.03183215  0.00202784  0.12008562
  0.05340

98 ######
0.011066113316692557
[-0.03968966 -0.02301178 -0.04030165 -0.03796759 -0.02038802 -0.0314038
 -0.03794    -0.04168384 -0.01795928  0.00184233 -0.02941179  0.00344023
 -0.02791493 -0.02901345  0.00622922 -0.01453117 -0.01634231 -0.02223697
  0.00199405 -0.00477659 -0.04329542 -0.02558711 -0.04267695 -0.04021462
 -0.02345551 -0.03293798 -0.03804494 -0.04390452 -0.02425722 -0.01811655
  0.02042908]
99 ######
0.011065967731811267
[-0.03971081 -0.02301389 -0.04031218 -0.03799454 -0.02040481 -0.03138551
 -0.03794725 -0.04167711 -0.01795303  0.00184198 -0.0294102   0.00342537
 -0.02792127 -0.02901168  0.00622846 -0.01453169 -0.01635769 -0.0222308
  0.00199362 -0.00476162 -0.04325985 -0.02559186 -0.04268593 -0.04020255
 -0.02347818 -0.03291508 -0.03804133 -0.04389817 -0.02427337 -0.01813174
  0.02042914]


In [9]:
from sklearn.linear_model import LogisticRegression

lr1 = LogisticRegression(random_state=0, penalty='none').fit(data, train_y)
lr2 = LogisticRegression(random_state=0, penalty='l2').fit(data, train_y)

c:\users\young\anaconda3\envs\study\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\young\anaconda3\envs\study\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
lr1.coef_

array([[  316.37848285,   151.4229622 ,   324.13975465,   161.2011775 ,
         -148.81101821,   973.76017558,  -374.89819977,  -778.30114519,
          295.22923949,   328.84677296, -1075.56331898,   422.07215305,
         -314.54211295,  -679.00324082,   216.53859079,   372.46845816,
         -129.76629066,  -511.23441741,  -215.85515865,   614.32642001,
         -397.06155094,  -924.69861549,  -129.08076399,  -465.97479177,
          107.69792743,   248.71600429,  -328.82960147,  -553.23061992,
         -217.20681907, -1238.75682548]])

In [11]:
lr2.coef_

array([[-0.33959323, -0.3324814 , -0.31619422, -0.38415508, -0.1942301 ,
         0.53580951, -0.75830361, -0.85337633,  0.16949981,  0.37449158,
        -1.29453811,  0.30300204, -0.71504839, -0.88244554,  0.06239748,
         0.73100815, -0.23750998, -0.25108461,  0.08392654,  0.72630831,
        -0.89063267, -1.08602693, -0.67686454, -0.8596919 , -0.56072218,
        -0.03779392, -0.87076278, -0.68637943, -0.61672213, -0.67378698]])

In [12]:
p1

array([-0.05776567, -0.12609832, -0.13825666, -0.00411075,  0.02539181,
       -0.26500701, -0.13431961, -0.26880611, -0.1271788 ,  0.05404011,
       -0.17783606,  0.129101  , -0.10023613, -0.16979803,  0.03810437,
       -0.01213212,  0.08047859, -0.12555197,  0.02525771, -0.08094128,
       -0.51210037, -0.13135389, -0.16850573, -0.31585876,  0.02586304,
       -0.3244672 , -0.22044948, -0.28043456, -0.02313424,  0.039139  ,
        0.17160581])

In [13]:
p2

array([-0.03971081, -0.02301389, -0.04031218, -0.03799454, -0.02040481,
       -0.03138551, -0.03794725, -0.04167711, -0.01795303,  0.00184198,
       -0.0294102 ,  0.00342537, -0.02792127, -0.02901168,  0.00622846,
       -0.01453169, -0.01635769, -0.0222308 ,  0.00199362, -0.00476162,
       -0.04325985, -0.02559186, -0.04268593, -0.04020255, -0.02347818,
       -0.03291508, -0.03804133, -0.04389817, -0.02427337, -0.01813174,
        0.02042914])

In [14]:
print('nomal:', accuracy_score(test_y, np.array(list(map(lambda x: 1 if x > 0 else 0, t.values @ p1)))))
print('l2:', accuracy_score(test_y, np.array(list(map(lambda x: 1 if x > 0 else 0, t.values @ p2)))))
print('lr1:', accuracy_score(test_y, lr1.predict(test_X)) )
print('lr2:', accuracy_score(test_y, lr2.predict(test_X)) )

nomal: 0.9181286549707602
l2: 0.9064327485380117
lr1: 0.935672514619883
lr2: 0.9824561403508771


In [15]:
from keras import layers, models, optimizers
import keras.backend as K
from keras.regularizers import L1L2

m = models.Sequential()
m.add(layers.Dense(1, activation='sigmoid', kernel_regularizer=L1L2(l1=0, l2=0.01)))

m.compile(optimizer='adam',
         loss = 'binary_crossentropy'
         )

Using TensorFlow backend.


In [16]:
m.fit(data.values, train_y.values,
     epochs=150)

Epoch 1/150
398/398 [==============================] - 0s 845us/step - loss: 0.5039
Epoch 2/150
398/398 [==============================] - 0s 55us/step - loss: 0.4576
Epoch 3/150
398/398 [==============================] - 0s 58us/step - loss: 0.4195
Epoch 4/150
398/398 [==============================] - 0s 55us/step - loss: 0.3883
Epoch 5/150
398/398 [==============================] - 0s 58us/step - loss: 0.3619
Epoch 6/150
398/398 [==============================] - 0s 55us/step - loss: 0.3401
Epoch 7/150
398/398 [==============================] - 0s 58us/step - loss: 0.3216
Epoch 8/150
398/398 [==============================] - 0s 59us/step - loss: 0.3055
Epoch 9/150
398/398 [==============================] - 0s 58us/step - loss: 0.2915
Epoch 10/150
398/398 [==============================] - 0s 58us/step - loss: 0.2794
Epoch 11/150
398/398 [==============================] - 0s 55us/step - loss: 0.2687
Epoch 12/150
398/398 [==============================] - 0s 63us/step - loss: 0.2591


398/398 [==============================] - 0s 58us/step - loss: 0.1347
Epoch 99/150
398/398 [==============================] - 0s 60us/step - loss: 0.1346
Epoch 100/150
398/398 [==============================] - 0s 60us/step - loss: 0.1344
Epoch 101/150
398/398 [==============================] - 0s 53us/step - loss: 0.1342
Epoch 102/150
398/398 [==============================] - 0s 58us/step - loss: 0.1340
Epoch 103/150
398/398 [==============================] - 0s 60us/step - loss: 0.1338
Epoch 104/150
398/398 [==============================] - 0s 60us/step - loss: 0.1336
Epoch 105/150
398/398 [==============================] - 0s 60us/step - loss: 0.1334
Epoch 106/150
398/398 [==============================] - 0s 60us/step - loss: 0.1333
Epoch 107/150
398/398 [==============================] - 0s 58us/step - loss: 0.1331
Epoch 108/150
398/398 [==============================] - 0s 60us/step - loss: 0.1330
Epoch 109/150
398/398 [==============================] - 0s 60us/step - loss: 0.

In [17]:
accuracy_score(test_y, m.predict_classes(test_X))

0.9824561403508771

In [18]:
## 직접 퍼셉트론까지 구현
class Percep:
    def __init__(self, x, y, activation='linear'):
        np.random.seed(0)
        self.data = x
        self.target = y
        self.w = np.random.normal(0, 1, len(x.values[0]))
        self.activation = activation
        self.loss = np.Inf
        self.hist = []
        
    def fit(self):           
        for _ in range(5000):
            w, c = self.logit(self.data, self.target, self.w)
            self.hist.append(c)
            if np.abs(c-self.loss) < 1e-4:
                break
            else:
                self.w = w
                self.loss = c
                
    def predict(self, data):
        return np.array(list(map(lambda x: 1 if x > 0 else 0, data.values @ self.w)))
    
    def logit(self, x, y, w=False, lr=0.01):
        t = np.array(list(map(lambda x: 1/(1 + np.exp(-x)), x@w))) - y.flatten()
        res = t.T @ x
#         np.array(list(map(lambda x: 1 if 1/(1+x) > 0 else 0, t.T @ x)))
        return w + np.dot(res, lr/len(x)), np.sum(res)/len(x)

                       

In [19]:
nn = Percep(d, train_y.values, activation='logit')

In [20]:
nn.fit()

In [21]:
nn.predict(d)

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,