In [1]:
import keras
from keras import models, layers
import keras.backend as K
from keras import regularizers
import numpy as np

np.random.seed(0)
# K.set_session(0)

Using TensorFlow backend.


In [2]:
from sklearn.datasets import load_iris, load_breast_cancer
import pandas as pd
data = pd.DataFrame(load_iris().data, columns=load_iris().feature_names)
target = load_iris().target
data = (data - np.mean(data)) / np.std(data)

In [3]:
data, target = load_breast_cancer(return_X_y=True)
data = (data - np.mean(data))/ np.std(data)

In [4]:
es = keras.callbacks.EarlyStopping(patience=50, monitor='val_loss', restore_best_weights=True)

In [5]:
input_layer = layers.Input(shape = (data.shape[1],))
x = layers.Dense(3, activation='relu')(input_layer)
x = layers.Dense(2, activation='sigmoid')(x)
x = layers.Dense(3, activation='relu')(x)
out = layers.Dense(data.shape[1], activation='linear')(x)

m1 = models.Model(input_layer, out)

m1.compile(optimizer = 'adam',
          loss = 'mse')

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
m1.fit(data, data,
      epochs=1000,
       validation_split=0.3,
       callbacks=[es]
      )

Instructions for updating:
Use tf.cast instead.
Train on 398 samples, validate on 171 samples
Epoch 1/1000
398/398 [==============================] - 1s 3ms/step - loss: 1.0220 - val_loss: 0.7907
Epoch 2/1000
398/398 [==============================] - 0s 73us/step - loss: 1.0017 - val_loss: 0.7733
Epoch 3/1000
398/398 [==============================] - 0s 85us/step - loss: 0.9818 - val_loss: 0.7558
Epoch 4/1000
398/398 [==============================] - 0s 83us/step - loss: 0.9617 - val_loss: 0.7381
Epoch 5/1000
398/398 [==============================] - 0s 85us/step - loss: 0.9406 - val_loss: 0.7197
Epoch 6/1000
398/398 [==============================] - 0s 83us/step - loss: 0.9190 - val_loss: 0.7007
Epoch 7/1000
398/398 [==============================] - 0s 83us/step - loss: 0.8970 - val_loss: 0.6810
Epoch 8/1000
398/398 [==============================] - 0s 75us/step - loss: 0.8739 - val_loss: 0.6612
Epoch 9/1000
398/398 [==============================] - 0s 88us/step - loss: 0.8508

Epoch 77/1000
398/398 [==============================] - 0s 100us/step - loss: 0.1316 - val_loss: 0.1097
Epoch 78/1000
398/398 [==============================] - 0s 85us/step - loss: 0.1282 - val_loss: 0.1073
Epoch 79/1000
398/398 [==============================] - 0s 93us/step - loss: 0.1251 - val_loss: 0.1052
Epoch 80/1000
398/398 [==============================] - 0s 85us/step - loss: 0.1219 - val_loss: 0.1030
Epoch 81/1000
398/398 [==============================] - 0s 98us/step - loss: 0.1190 - val_loss: 0.1009
Epoch 82/1000
398/398 [==============================] - 0s 148us/step - loss: 0.1161 - val_loss: 0.0988
Epoch 83/1000
398/398 [==============================] - 0s 80us/step - loss: 0.1132 - val_loss: 0.0968
Epoch 84/1000
398/398 [==============================] - 0s 123us/step - loss: 0.1104 - val_loss: 0.0947
Epoch 85/1000
398/398 [==============================] - 0s 88us/step - loss: 0.1077 - val_loss: 0.0927
Epoch 86/1000
398/398 [==============================] - 0s 6

398/398 [==============================] - 0s 73us/step - loss: 0.0291 - val_loss: 0.0348
Epoch 155/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0286 - val_loss: 0.0345
Epoch 156/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0282 - val_loss: 0.0342
Epoch 157/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0279 - val_loss: 0.0339
Epoch 158/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0275 - val_loss: 0.0335
Epoch 159/1000
398/398 [==============================] - 0s 150us/step - loss: 0.0271 - val_loss: 0.0332
Epoch 160/1000
398/398 [==============================] - 0s 155us/step - loss: 0.0267 - val_loss: 0.0328
Epoch 161/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0263 - val_loss: 0.0325
Epoch 162/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0260 - val_loss: 0.0322
Epoch 163/1000
398/398 [==============================] - 0s 88us/st

Epoch 232/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0129 - val_loss: 0.0191
Epoch 233/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0128 - val_loss: 0.0190
Epoch 234/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0127 - val_loss: 0.0189
Epoch 235/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0126 - val_loss: 0.0188
Epoch 236/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0125 - val_loss: 0.0187
Epoch 237/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0124 - val_loss: 0.0186
Epoch 238/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0123 - val_loss: 0.0185
Epoch 239/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0123 - val_loss: 0.0184
Epoch 240/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0122 - val_loss: 0.0183
Epoch 241/1000
398/398 [==============================]

398/398 [==============================] - 0s 113us/step - loss: 0.0091 - val_loss: 0.0134
Epoch 310/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0091 - val_loss: 0.0134
Epoch 311/1000
398/398 [==============================] - 0s 113us/step - loss: 0.0091 - val_loss: 0.0133
Epoch 312/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0090 - val_loss: 0.0133
Epoch 313/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0090 - val_loss: 0.0132
Epoch 314/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0090 - val_loss: 0.0132
Epoch 315/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0090 - val_loss: 0.0132
Epoch 316/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0090 - val_loss: 0.0131
Epoch 317/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0089 - val_loss: 0.0131
Epoch 318/1000
398/398 [==============================] - 0s 83us/st

398/398 [==============================] - 0s 70us/step - loss: 0.0078 - val_loss: 0.0105
Epoch 388/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0078 - val_loss: 0.0104
Epoch 389/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0077 - val_loss: 0.0104
Epoch 390/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0077 - val_loss: 0.0104
Epoch 391/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0077 - val_loss: 0.0104
Epoch 392/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0077 - val_loss: 0.0103
Epoch 393/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0077 - val_loss: 0.0103
Epoch 394/1000
398/398 [==============================] - 0s 65us/step - loss: 0.0077 - val_loss: 0.0103
Epoch 395/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0077 - val_loss: 0.0102
Epoch 396/1000
398/398 [==============================] - 0s 70us/step

398/398 [==============================] - 0s 70us/step - loss: 0.0071 - val_loss: 0.0087
Epoch 466/1000
398/398 [==============================] - 0s 65us/step - loss: 0.0071 - val_loss: 0.0088
Epoch 467/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0071 - val_loss: 0.0087
Epoch 468/1000
398/398 [==============================] - 0s 63us/step - loss: 0.0071 - val_loss: 0.0087
Epoch 469/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0071 - val_loss: 0.0087
Epoch 470/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0071 - val_loss: 0.0086
Epoch 471/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0070 - val_loss: 0.0086
Epoch 472/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0071 - val_loss: 0.0086
Epoch 473/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0070 - val_loss: 0.0086
Epoch 474/1000
398/398 [==============================] - 0s 73us/step

398/398 [==============================] - 0s 65us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 544/1000
398/398 [==============================] - 0s 65us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 545/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 546/1000
398/398 [==============================] - 0s 95us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 547/1000
398/398 [==============================] - 0s 108us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 548/1000
398/398 [==============================] - 0s 138us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 549/1000
398/398 [==============================] - 0s 128us/step - loss: 0.0067 - val_loss: 0.0076
Epoch 550/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0066 - val_loss: 0.0075
Epoch 551/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0066 - val_loss: 0.0075
Epoch 552/1000
398/398 [==============================] - 0s 85us/s

398/398 [==============================] - 0s 70us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 622/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 623/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 624/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 625/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 626/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 627/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 628/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0064 - val_loss: 0.0067
Epoch 629/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0064 - val_loss: 0.0068
Epoch 630/1000
398/398 [==============================] - 0s 75us/step

398/398 [==============================] - 0s 70us/step - loss: 0.0062 - val_loss: 0.0062
Epoch 700/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0062 - val_loss: 0.0062
Epoch 701/1000
398/398 [==============================] - 0s 98us/step - loss: 0.0062 - val_loss: 0.0062
Epoch 702/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0062 - val_loss: 0.0061
Epoch 703/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0062 - val_loss: 0.0061
Epoch 704/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0062 - val_loss: 0.0061
Epoch 705/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0062 - val_loss: 0.0062
Epoch 706/1000
398/398 [==============================] - 0s 70us/step - loss: 0.0062 - val_loss: 0.0061
Epoch 707/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0062 - val_loss: 0.0061
Epoch 708/1000
398/398 [==============================] - 0s 75us/step

Epoch 777/1000
398/398 [==============================] - 0s 100us/step - loss: 0.0062 - val_loss: 0.0058
Epoch 778/1000
398/398 [==============================] - 0s 118us/step - loss: 0.0062 - val_loss: 0.0058
Epoch 779/1000
398/398 [==============================] - 0s 115us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 780/1000
398/398 [==============================] - 0s 123us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 781/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 782/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 783/1000
398/398 [==============================] - 0s 90us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 784/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 785/1000
398/398 [==============================] - 0s 68us/step - loss: 0.0061 - val_loss: 0.0058
Epoch 786/1000
398/398 [===========================

Epoch 855/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 856/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 857/1000
398/398 [==============================] - 0s 75us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 858/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 859/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 860/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 861/1000
398/398 [==============================] - 0s 73us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 862/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 863/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 864/1000
398/398 [==============================]

398/398 [==============================] - 0s 103us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 933/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 934/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 935/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 936/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 937/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 938/1000
398/398 [==============================] - 0s 98us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 939/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 940/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0061 - val_loss: 0.0056
Epoch 941/1000
398/398 [==============================] - 0s 85us/ste

In [7]:
m1.predict(data)

array([[-0.18207383, -0.17452732,  0.3147136 , ..., -0.27028897,
        -0.26931387, -0.2707711 ],
       [-0.18048656, -0.17401059,  0.3267709 , ..., -0.27028164,
        -0.2693136 , -0.2707725 ],
       [-0.18477368, -0.17548674,  0.29457515, ..., -0.2703047 ,
        -0.2693177 , -0.270769  ],
       ...,
       [-0.19821116, -0.18165275,  0.20073551, ..., -0.27043918,
        -0.26939502, -0.27076468],
       [-0.18262793, -0.1747158 ,  0.3105418 , ..., -0.27029186,
        -0.2693143 , -0.2707706 ],
       [-0.23023924, -0.20023666, -0.00506452, ..., -0.27091664,
        -0.26974234, -0.2707711 ]], dtype=float32)

In [8]:
data

array([[-0.19229615, -0.22562986,  0.26679799, ..., -0.26993435,
        -0.26908152, -0.27057606],
       [-0.1809951 , -0.19325981,  0.31103852, ..., -0.27028214,
        -0.2698923 , -0.27070694],
       [-0.18484972, -0.17801653,  0.29833579, ..., -0.27003247,
        -0.26951429, -0.27071325],
       ...,
       [-0.1983847 , -0.14809942,  0.20328434, ..., -0.27047575,
        -0.27012533, -0.27075434],
       [-0.1808637 , -0.1426241 ,  0.34257633, ..., -0.26993611,
        -0.26930666, -0.27055372],
       [-0.23710612, -0.16360551, -0.06119523, ..., -0.27109687,
        -0.2698393 , -0.27078855]])

In [9]:
def sampling(args):
    """Reparameterization trick by sampling from an isotropic unit Gaussian.
    # Arguments
        args (tensor): mean and log of variance of Q(z|X)
    # Returns
        z (tensor): sampled latent vector
    """

    z_mean, z_log_var = args
    batch = K.shape(z_mean)[0]
    dim = K.int_shape(z_mean)[1]
    # by default, random_normal has mean = 0 and std = 1.0
    epsilon = K.random_normal(shape=(batch, dim))
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

In [10]:
from keras.layers import Dense, Input, Lambda
from keras.models import Model

In [11]:
input_shape =(data.shape[1],)
intermediate_dim = 8
latent_dim = 2
original_dim = data.shape[1]


inputs = Input(shape=input_shape, name='encoder_input')
x = Dense(intermediate_dim, activation='relu')(inputs)
z_mean = Dense(latent_dim, name='z_mean')(x)
z_log_var = Dense(latent_dim, name='z_log_var')(x)

# use reparameterization trick to push the sampling out as input
# note that "output_shape" isn't necessary with the TensorFlow backend
z = Lambda(sampling, output_shape=(latent_dim,), name='z')([z_mean, z_log_var])

# instantiate encoder model
encoder = Model(inputs, z, name='encoder')
encoder.summary()
# plot_model(encoder, to_file='vae_mlp_encoder.png', show_shapes=True)

# build decoder model
latent_inputs = Input(shape=(latent_dim,), name='z_sampling')
x = Dense(intermediate_dim, activation='relu')(latent_inputs)
outputs = Dense(original_dim, activation='linear')(x)

# instantiate decoder model
decoder = Model(latent_inputs, outputs, name='decoder')
decoder.summary()
# plot_model(decoder, to_file='vae_mlp_decoder.png', show_shapes=True)

# instantiate VAE model
outputs = decoder(encoder(inputs))
vae = models.Model(inputs, outputs, name='vae_mlp')

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input (InputLayer)      (None, 30)           0                                            
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 8)            248         encoder_input[0][0]              
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            18          dense_5[0][0]                    
__________________________________________________________________________________________________
z_log_var (Dense)               (None, 2)            18          dense_5[0][0]                    
__________________________________________________________________________________________________
z (Lambda)

In [12]:
vae.compile(optimizer = 'adam',
           loss = 'mae')

In [13]:
for l in decoder.layers[1:]:
    print(l.get_weights())

[array([[ 0.18779635, -0.57841504, -0.27668124, -0.03296393,  0.64246905,
        -0.5042311 ,  0.2587968 , -0.13367438],
       [ 0.7350595 , -0.67342055, -0.5093818 , -0.7352656 , -0.30044916,
         0.75774837, -0.7220092 ,  0.6106931 ]], dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]
[array([[ 0.287461  , -0.0796026 ,  0.32286736, -0.2721782 , -0.21911728,
         0.28855875, -0.36318317,  0.08224371, -0.39588246,  0.39530286,
         0.16346446,  0.3632296 , -0.14187366,  0.32385018,  0.13968435,
         0.22305486, -0.18421148,  0.0291068 , -0.04482695, -0.396546  ,
        -0.33039495,  0.08956912, -0.37845674,  0.24159405, -0.18744288,
         0.23625991,  0.06439516, -0.3666754 ,  0.36217335,  0.01277807],
       [-0.23770194, -0.07453316, -0.35155693,  0.32065824, -0.28342634,
        -0.03542459,  0.05483243,  0.35413656, -0.20873477,  0.14761534,
         0.04119754, -0.04188669,  0.07563052, -0.36718604, -0.36834082,
         0.07864782,  0.1

In [14]:
for l in decoder.layers[1:]:
    print(l.get_weights())

[array([[ 0.18779635, -0.57841504, -0.27668124, -0.03296393,  0.64246905,
        -0.5042311 ,  0.2587968 , -0.13367438],
       [ 0.7350595 , -0.67342055, -0.5093818 , -0.7352656 , -0.30044916,
         0.75774837, -0.7220092 ,  0.6106931 ]], dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]
[array([[ 0.287461  , -0.0796026 ,  0.32286736, -0.2721782 , -0.21911728,
         0.28855875, -0.36318317,  0.08224371, -0.39588246,  0.39530286,
         0.16346446,  0.3632296 , -0.14187366,  0.32385018,  0.13968435,
         0.22305486, -0.18421148,  0.0291068 , -0.04482695, -0.396546  ,
        -0.33039495,  0.08956912, -0.37845674,  0.24159405, -0.18744288,
         0.23625991,  0.06439516, -0.3666754 ,  0.36217335,  0.01277807],
       [-0.23770194, -0.07453316, -0.35155693,  0.32065824, -0.28342634,
        -0.03542459,  0.05483243,  0.35413656, -0.20873477,  0.14761534,
         0.04119754, -0.04188669,  0.07563052, -0.36718604, -0.36834082,
         0.07864782,  0.1

In [15]:
decoder.get_weights()

[array([[ 0.18779635, -0.57841504, -0.27668124, -0.03296393,  0.64246905,
         -0.5042311 ,  0.2587968 , -0.13367438],
        [ 0.7350595 , -0.67342055, -0.5093818 , -0.7352656 , -0.30044916,
          0.75774837, -0.7220092 ,  0.6106931 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.287461  , -0.0796026 ,  0.32286736, -0.2721782 , -0.21911728,
          0.28855875, -0.36318317,  0.08224371, -0.39588246,  0.39530286,
          0.16346446,  0.3632296 , -0.14187366,  0.32385018,  0.13968435,
          0.22305486, -0.18421148,  0.0291068 , -0.04482695, -0.396546  ,
         -0.33039495,  0.08956912, -0.37845674,  0.24159405, -0.18744288,
          0.23625991,  0.06439516, -0.3666754 ,  0.36217335,  0.01277807],
        [-0.23770194, -0.07453316, -0.35155693,  0.32065824, -0.28342634,
         -0.03542459,  0.05483243,  0.35413656, -0.20873477,  0.14761534,
          0.04119754, -0.04188669,  0.07563052, -0.36718604, -0.36834082,
          0.0

In [16]:
vae.fit(data, data, 
       epochs = 1000, 
       validation_split=0.3,
       callbacks=[es])

Train on 398 samples, validate on 171 samples
Epoch 1/1000
398/398 [==============================] - 2s 5ms/step - loss: 0.5101 - val_loss: 0.4551
Epoch 2/1000
398/398 [==============================] - 0s 88us/step - loss: 0.4651 - val_loss: 0.4089
Epoch 3/1000
398/398 [==============================] - 0s 93us/step - loss: 0.4326 - val_loss: 0.3900
Epoch 4/1000
398/398 [==============================] - 0s 95us/step - loss: 0.4062 - val_loss: 0.3615
Epoch 5/1000
398/398 [==============================] - 0s 95us/step - loss: 0.3804 - val_loss: 0.3437
Epoch 6/1000
398/398 [==============================] - 0s 93us/step - loss: 0.3587 - val_loss: 0.3222
Epoch 7/1000
398/398 [==============================] - 0s 98us/step - loss: 0.3407 - val_loss: 0.3049
Epoch 8/1000
398/398 [==============================] - 0s 103us/step - loss: 0.3238 - val_loss: 0.2889
Epoch 9/1000
398/398 [==============================] - 0s 115us/step - loss: 0.3059 - val_loss: 0.2710
Epoch 10/1000
398/398 [===

398/398 [==============================] - 0s 103us/step - loss: 0.0174 - val_loss: 0.0147
Epoch 80/1000
398/398 [==============================] - 0s 93us/step - loss: 0.0172 - val_loss: 0.0144
Epoch 81/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0174 - val_loss: 0.0149
Epoch 82/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0171 - val_loss: 0.0146
Epoch 83/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0173 - val_loss: 0.0146
Epoch 84/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0169 - val_loss: 0.0143
Epoch 85/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0170 - val_loss: 0.0138
Epoch 86/1000
398/398 [==============================] - 0s 90us/step - loss: 0.0169 - val_loss: 0.0142
Epoch 87/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0171 - val_loss: 0.0145
Epoch 88/1000
398/398 [==============================] - 0s 85us/step - loss:

398/398 [==============================] - 0s 130us/step - loss: 0.0143 - val_loss: 0.0117
Epoch 158/1000
398/398 [==============================] - 0s 123us/step - loss: 0.0143 - val_loss: 0.0115
Epoch 159/1000
398/398 [==============================] - 0s 130us/step - loss: 0.0140 - val_loss: 0.0112
Epoch 160/1000
398/398 [==============================] - 0s 148us/step - loss: 0.0141 - val_loss: 0.0112
Epoch 161/1000
398/398 [==============================] - 0s 110us/step - loss: 0.0140 - val_loss: 0.0111
Epoch 162/1000
398/398 [==============================] - 0s 118us/step - loss: 0.0141 - val_loss: 0.0114
Epoch 163/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0139 - val_loss: 0.0110
Epoch 164/1000
398/398 [==============================] - 0s 78us/step - loss: 0.0140 - val_loss: 0.0110
Epoch 165/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0140 - val_loss: 0.0118
Epoch 166/1000
398/398 [==============================] - 0s 83u

Epoch 235/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0072 - val_loss: 0.0063
Epoch 236/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0072 - val_loss: 0.0060
Epoch 237/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0072 - val_loss: 0.0068
Epoch 238/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0071 - val_loss: 0.0060
Epoch 239/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0069 - val_loss: 0.0059
Epoch 240/1000
398/398 [==============================] - 0s 90us/step - loss: 0.0069 - val_loss: 0.0060
Epoch 241/1000
398/398 [==============================] - 0s 110us/step - loss: 0.0071 - val_loss: 0.0061
Epoch 242/1000
398/398 [==============================] - 0s 125us/step - loss: 0.0069 - val_loss: 0.0061
Epoch 243/1000
398/398 [==============================] - 0s 103us/step - loss: 0.0069 - val_loss: 0.0059
Epoch 244/1000
398/398 [============================

Epoch 313/1000
398/398 [==============================] - 0s 90us/step - loss: 0.0057 - val_loss: 0.0057
Epoch 314/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0056 - val_loss: 0.0054
Epoch 315/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0055 - val_loss: 0.0053
Epoch 316/1000
398/398 [==============================] - 0s 88us/step - loss: 0.0055 - val_loss: 0.0051
Epoch 317/1000
398/398 [==============================] - 0s 85us/step - loss: 0.0055 - val_loss: 0.0053
Epoch 318/1000
398/398 [==============================] - 0s 90us/step - loss: 0.0054 - val_loss: 0.0052
Epoch 319/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0054 - val_loss: 0.0053
Epoch 320/1000
398/398 [==============================] - 0s 80us/step - loss: 0.0055 - val_loss: 0.0055
Epoch 321/1000
398/398 [==============================] - 0s 83us/step - loss: 0.0056 - val_loss: 0.0056
Epoch 322/1000
398/398 [==============================]

In [17]:
vae.predict(data)

array([[-0.19344081, -0.16058354,  0.23498751, ..., -0.27154154,
        -0.26682103, -0.27443838],
       [-0.17688283, -0.16183037,  0.33845806, ..., -0.2715966 ,
        -0.26740122, -0.27535632],
       [-0.18241058, -0.1666806 ,  0.30213243, ..., -0.27157745,
        -0.2678093 , -0.27483627],
       ...,
       [-0.19876875, -0.17823267,  0.19558299, ..., -0.2715212 ,
        -0.26869673, -0.27341062],
       [-0.17937428, -0.1644214 ,  0.32194862, ..., -0.27158788,
        -0.26763162, -0.27510563],
       [-0.23240407, -0.19521241, -0.02120905, ..., -0.27140656,
        -0.2697476 , -0.27075404]], dtype=float32)

In [18]:
data

array([[-0.19229615, -0.22562986,  0.26679799, ..., -0.26993435,
        -0.26908152, -0.27057606],
       [-0.1809951 , -0.19325981,  0.31103852, ..., -0.27028214,
        -0.2698923 , -0.27070694],
       [-0.18484972, -0.17801653,  0.29833579, ..., -0.27003247,
        -0.26951429, -0.27071325],
       ...,
       [-0.1983847 , -0.14809942,  0.20328434, ..., -0.27047575,
        -0.27012533, -0.27075434],
       [-0.1808637 , -0.1426241 ,  0.34257633, ..., -0.26993611,
        -0.26930666, -0.27055372],
       [-0.23710612, -0.16360551, -0.06119523, ..., -0.27109687,
        -0.2698393 , -0.27078855]])

In [19]:
encoder.predict(data)

array([[9.293605  , 5.86291   ],
       [8.954542  , 7.4143248 ],
       [7.7888527 , 6.6442094 ],
       ...,
       [5.0193577 , 4.4980054 ],
       [8.33084   , 7.0478535 ],
       [0.9638843 , 0.45909384]], dtype=float32)

In [20]:
encoder.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input (InputLayer)      (None, 30)           0                                            
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 8)            248         encoder_input[0][0]              
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            18          dense_5[0][0]                    
__________________________________________________________________________________________________
z_log_var (Dense)               (None, 2)            18          dense_5[0][0]                    
__________________________________________________________________________________________________
z (Lambda)

In [21]:
data

array([[-0.19229615, -0.22562986,  0.26679799, ..., -0.26993435,
        -0.26908152, -0.27057606],
       [-0.1809951 , -0.19325981,  0.31103852, ..., -0.27028214,
        -0.2698923 , -0.27070694],
       [-0.18484972, -0.17801653,  0.29833579, ..., -0.27003247,
        -0.26951429, -0.27071325],
       ...,
       [-0.1983847 , -0.14809942,  0.20328434, ..., -0.27047575,
        -0.27012533, -0.27075434],
       [-0.1808637 , -0.1426241 ,  0.34257633, ..., -0.26993611,
        -0.26930666, -0.27055372],
       [-0.23710612, -0.16360551, -0.06119523, ..., -0.27109687,
        -0.2698393 , -0.27078855]])