In [1]:
import numpy as np

In [2]:
obj = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]
obj = np.array(obj)

In [3]:
obj

array([[0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0]])

In [4]:
def pi(a):
    for i in range(len(a)):
        if a[i] == np.nan:
            a[i] = 0
            
    s = np.nansum(a)
    if s == 0:
        s = 1e-5
        print('here')
    for i in range(len(a)):
        a[i] /= s
    return a

def get_pi(a):
    for i in range(len(a)):
        for j in range(len(a[0])):
            a[i][j] = pi(a[i][j])
    return a

In [5]:
def action(s):
    # eps는 사전 설정
    ## s_next 생성
    if np.random.rand() > eps:
        return np.argmax(v[s])
    else:
        return np.random.choice([0, 1, 2, 3]) # 상하좌우
    
def state_map(s, a):
    s = list(s)
    if a == 0:
        s[0] -= 1
    elif a == 1:
        s[0] += 1
    elif a == 2:
        s[1] -= 1
    else:
        s[1] += 1
    return tuple(s)


In [6]:
def update(s, a, r, s_next, v):
    # lr, gamma 는 위에서 설정하기
    if s_next == goal:
        v[s][a] = v[s][a] + lr * (r - v[s][a])
    else:
        v[s][a] = v[s][a] + lr * (r + gamma*np.max(v[s_next]) - v[s][a])
        
#     v[s] = pi(v[s])
    return v


In [7]:
def is_wall(s):
    if s[0] < 0 or s[0] > 3:
        return True
    elif s[1] < 0 or s[1] > 4:
        return True
    elif obj[s] == 1:
        return True
    else:
        return False

In [8]:
def play(s):
    global v, fail_hist, hist, eps
    
    while 1:
        eps -= 0.01
        temp_hist.append(s)
#         print(s)
        a = action(s)
        s_next = state_map(s, a)
#         print(a, s, s_next)
        
#         if (0 > s[0] or s[0] > 3) or (0 > s[1] or s[1] > 4) or obj[s] == 1: ## 가면 안되는 곳
        if is_wall(s_next):
            fail_hist.append((s, s_next))
#             r = -1
            v[s][a] = 0
            v[s] = pi(v[s])
#             v = update(s, a, r, s_next, v)
#             print(v[s], s_next)
            s_next = (0, 0)
            
            
        elif s_next[0] == goal[0] and s_next[1] == goal[1]: ## 도착
            r = 1
            v = update(s, a, r, s_next, v)
            break
        else: ## 갈곳이 남음
            r = 0
            v = update(s, a, r , s_next, v)
            
        print(v[s])
        fake_obj[s_next] = 2
        print(fake_obj)
        fake_obj[s_next] = obj[s_next]
        print(eps)
            
        s = s_next
        
    hist.append(temp_hist)

In [9]:
shape = obj.shape
value = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]
for i in range(shape[0]):
    for j in range(shape[1]):
        value[i][j] = [0.25, 0.25, 0.25, 0.25] # 위, 아래, 좌, 우
v = np.array(value)

In [14]:
lr = 0.1
eps = 0.5
gamma = 0.9
v = np.array(value)
fail_hist = []
hist = []
fake_obj = obj.copy()

s_0 = (0, 0)
goal = (3, 4)

for i in range(100):
    play(s_0)
    print('succes', i)
    print(eps)
#     eps = 0.5

[0.         0.33333333 0.33333333 0.33333333]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.49
[0.         0.3225     0.33333333 0.33333333]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.48
[0.255 0.25  0.25  0.25 ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47
[0.         0.49174079 0.         0.50825921]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.45999999999999996
[0.         0.49174079 0.         0.50825921]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.44999999999999996
[0.         0.49174079 0.         0.47993329]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.43999999999999995
[0.         0.33333333 0.33333333 0.33333333]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.42999999999999994
[0.         0.46551671 0.         0.47993329]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.41999999999999993
[0.33774834 0.33112583 0.         0.33112583]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.409999999999

 [0 0 1 1 0]]
-1.7700000000000016
[0.         0.         0.34405379 0.34431902]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.7800000000000016
[0.         0.         0.34382449 0.34577256]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.7900000000000016
[0.         0.34382298 0.         0.34573732]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8000000000000016
[0.34041142 0.33112583 0.         0.33112583]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8100000000000016
[0.         0.34382298 0.         0.34228312]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8200000000000016
[0.         0.         0.34382449 0.34218401]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8300000000000016
[0.         0.         0.34405379 0.34036845]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8400000000000016
[0.         0.3225     0.33577815 0.33333333]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-1.8500000000000016
[0.         0.

 [0 0 1 1 0]]
-4.3599999999999515
[0.         0.         0.30957695 0.30811522]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.369999999999951
[0.         0.         0.3100656  0.30973753]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.379999999999951
[0.         0.30923778 0.31106885 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.389999999999951
[0.303835 0.25     0.25     0.25    ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.399999999999951
[0.         0.30923778 0.30786787 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.40999999999995
[0.         0.         0.30692096 0.30973753]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.41999999999995
[0.         0.         0.30639084 0.30811522]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.42999999999995
[0.         0.30553438 0.         0.30746986]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-4.43999999999995
[0.30736336 0.30552734 0.         

[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.729999999999901
[0.         0.         0.25302683 0.25290736]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.739999999999901
[0.         0.2523459  0.25364744 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7499999999999005
[0.25150183 0.25       0.25       0.25      ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7599999999999
[0.         0.2523459  0.25105511 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7699999999999
[0.         0.         0.25047145 0.25290736]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7799999999999
[0.         0.         0.25021905 0.25265467]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7899999999999
[0.         0.25017823 0.         0.25224323]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-6.7999999999998995
[0.25192655 0.24984768 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-6.809999

[0.30167235 0.30563871 0.         0.30623775]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-9.679999999999838
[0.24674881 0.27245752 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-9.689999999999838
[0.30167235 0.30563871 0.         0.30256044]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
-9.699999999999838
[0.         0.29921718 0.29697217 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-9.709999999999837
[0.30167235 0.30333267 0.         0.30256044]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-9.719999999999837
[0.30987825 0.         0.         0.30957719]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-9.729999999999837
[0.30167235 0.30088845 0.         0.30256044]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-9.739999999999837
[0.30612086 0.         0.         0.30957719]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-9.749999999999837
[0.30167235 0.30088845 0.         0.29923394]
[[0 0 0 0 

[0.27865823 0.         0.28102479 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
-12.359999999999781
[0.         0.277812   0.25383616 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-12.36999999999978
[0.27865823 0.         0.27808938 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-12.37999999999978
[0.26913933 0.         0.         0.27674995]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-12.38999999999978
[0.27579549 0.         0.27808938 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
-12.39999999999978
[0.         0.27505884 0.25383616 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-12.40999999999978
[0.27579549 0.         0.27518794 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-12.41999999999978
[0.26913933 0.         0.         0.27389655]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-12.42999999999978
[0.27297123 0.         0.27518794 0.        ]
[[0 0 0 0

[0.44987802 0.         0.         0.44092268]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-15.529999999999713
[0.30093757 0.25       0.25       0.25      ]
[[0 0 0 0 1]
 [0 1 1 0 2]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-15.539999999999713
[0.         0.31354339 0.31613617 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-15.549999999999713
[0.31480237 0.37426209 0.         0.31667135]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-15.559999999999713
[0.43857381 0.         0.         0.44092268]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-15.569999999999713
[0.31480237 0.37651892 0.         0.31667135]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-15.579999999999712
[0.43857381 0.         0.         0.42391479]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-15.589999999999712
[0.29929607 0.25       0.25       0.25      ]
[[0 0 0 0 1]
 [0 1 1 0 2]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-15.599999999999712
[0.         0.31354339 0.31840926 0.        ]
[[

[0.         0.21868645 0.         0.21729612]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-18.67000000000012
[0.         0.         0.22505832 0.22596489]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-18.68000000000012
[0.         0.         0.23614952 0.23790223]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-18.690000000000122
[0.         0.24958158 0.24572516 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-18.700000000000124
[0.25761992 0.25831275 0.         0.25816126]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-18.710000000000125
[0.26912615 0.         0.         0.29255254]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-18.720000000000127
succes 3
-18.73000000000013
[0.         0.21650506 0.         0.21729612]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-18.74000000000013
[0.21831668 0.21660517 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-18.75000000000013
[0.21752877 0.21775499 0

succes 16
-20.98000000000048
[0.         0.19600601 0.         0.19736315]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-20.99000000000048
[0.19724974 0.19638244 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-21.000000000000483
[0.19709561 0.19681626 0.         0.19817796]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-21.010000000000485
[0.19854184 0.         0.         0.19670856]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-21.020000000000486
[0.1974966 0.        0.1966439 0.       ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
-21.030000000000488
[0.19652367 0.         0.         0.19670856]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
-21.04000000000049
[0.19709561 0.19681626 0.         0.19617447]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
-21.05000000000049
[0.         0.19591777 0.19709378 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
-21.060000000000493
[0.19548538 0.         0.1

 [0 0 1 1 0]]
-23.560000000000883
[0.26912615 0.         0.         0.87537156]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-23.570000000000885
succes 48
-23.580000000000886
[0.         0.19217304 0.         0.25194267]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-23.590000000000888
[0.         0.         0.20909871 0.33680716]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-23.60000000000089
[0.         0.         0.225525   0.45511605]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-23.61000000000089
[0.         0.59723774 0.24208704 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-23.620000000000893
[0.25761992 0.74371086 0.         0.25816126]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-23.630000000000894
[0.26912615 0.         0.         0.87744787]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-23.640000000000896
succes 49
-23.650000000000897
[0.         0.19217304 0.         0.25706104]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0

[0.         0.72445891 0.24208704 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-27.05000000000143
[0.25761992 0.8087273  0.         0.25816126]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-27.06000000000143
[0.26912615 0.         0.         0.8997624 ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
-27.070000000001432
succes 98
-27.080000000001434
[0.         0.19217304 0.         0.48681759]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-27.090000000001435
[0.         0.         0.20909871 0.56588985]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-27.100000000001437
[0.         0.         0.225525   0.64474686]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-27.11000000000144
[0.         0.72479848 0.24208704 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
-27.12000000000144
[0.25761992 0.80883318 0.         0.25816126]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
-27.13000000000144
[0.26912615 0.         

In [15]:
v

array([[[0.        , 0.19217304, 0.        , 0.48681759],
        [0.        , 0.        , 0.20909871, 0.56588985],
        [0.        , 0.        , 0.225525  , 0.64474686],
        [0.        , 0.72479848, 0.24208704, 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ]],

       [[0.19147869, 0.19254735, 0.        , 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.25761992, 0.80883318, 0.        , 0.25816126],
        [0.        , 0.25498136, 0.25383623, 0.        ]],

       [[0.1912844 , 0.19288078, 0.        , 0.19222343],
        [0.        , 0.19194252, 0.1912439 , 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.26912615, 0.        , 0.        , 0.89978417],
        [0.24960671, 0.99998008, 0.25      , 0.25      ]],

       [[0.19255137, 0.        , 0.        , 0.19278209],
        [0.19153371, 0.        , 0.19270741, 0.        ],
        

In [ ]:
value = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]

In [17]:
eps

-27.150000000001445