In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris

from sklearn.metrics import silhouette_samples, silhouette_score

# load_iris().keys()
data = pd.DataFrame(load_iris().data, columns=load_iris().feature_names)
target = load_iris().target

In [2]:
# np.random.seed(13)
# init = data.iloc[list(np.random.choice(range(len(data)), 2, replace=False)), :].values

In [3]:
def mapping(d, target):
    dist = 1000
    res = None
    for i in range(len(target)):
#         print(type((d.values-target[i]).T @ (d-target[i])))
#         print(dist)
        if (d.values-target[i]).T @ (d-target[i]) < dist:
            res = i
            dist = (d.values-target[i]).T @ (d-target[i])
    return res

In [4]:
sils = []
for n in range(2, 10):
    np.random.seed(0)
    init = data.iloc[list(np.random.choice(range(len(data)), n, replace=False)), :].values
    c = 0
    d = -1
    for _ in range(50):
    #     print(c)
        cluster1 = []
        for i in range(len(data)):
            cluster1.append(mapping(data.iloc[i,:], init))
        temp_d = silhouette_score(data, cluster1)
        if d < temp_d:
            temp = pd.concat([data, pd.DataFrame(np.array(cluster1).reshape(-1, 1), columns=['cl'])], axis=1)
            init = temp.groupby('cl').mean().values
            c += 1
            d = temp_d
        else:
            print(silhouette_score(data, cluster1))
            print(init)
            temp = pd.DataFrame()
            temp['sils'] = silhouette_samples(data, cluster1)
            temp['cl'] = cluster1
            sils.append(temp)
            break

0.681046169211746
[[6.30103093 2.88659794 4.95876289 1.69587629]
 [5.00566038 3.36981132 1.56037736 0.29056604]]
0.5511916046195916
[[6.85384615 3.07692308 5.71538462 2.05384615]
 [5.88360656 2.74098361 4.38852459 1.43442623]
 [5.006      3.428      1.462      0.246     ]]
0.4953563285288493
[[6.29361702 2.9        4.95106383 1.72978723]
 [5.58       2.63333333 3.98666667 1.23333333]
 [5.006      3.428      1.462      0.246     ]
 [7.08695652 3.12608696 6.01304348 2.14347826]]
0.3640626192643996
[[6.29361702 2.9        4.95106383 1.72978723]
 [5.58       2.63333333 3.98666667 1.23333333]
 [5.37058824 3.8        1.51764706 0.27647059]
 [7.08695652 3.12608696 6.01304348 2.14347826]
 [4.81818182 3.23636364 1.43333333 0.23030303]]
0.36295529183027064
[[6.24722222 2.84722222 4.775      1.575     ]
 [5.53214286 2.63571429 3.96071429 1.22857143]
 [5.37058824 3.8        1.51764706 0.27647059]
 [7.475      3.125      6.3        2.05      ]
 [4.81818182 3.23636364 1.43333333 0.23030303]
 [6.5291

In [5]:
for i in range(len(sils)):
    print('#### cl: ', i)
    print(sils[i].groupby('cl')['sils'].mean())
    print()

#### cl:  0
cl
0    0.632701
1    0.769526
Name: sils, dtype: float64

#### cl:  1
cl
0    0.436842
1    0.422323
2    0.797604
Name: sils, dtype: float64

#### cl:  2
cl
0    0.311757
1    0.439199
2    0.766000
3    0.355432
Name: sils, dtype: float64

#### cl:  3
cl
0    0.311757
1    0.437451
2    0.377160
3    0.355432
4    0.371110
Name: sils, dtype: float64

#### cl:  4
cl
0    0.299765
1    0.397864
2    0.377160
3    0.342779
4    0.371110
5    0.405827
Name: sils, dtype: float64

#### cl:  5
cl
0    0.299765
1    0.397886
2    0.311010
3    0.342779
4    0.352082
5    0.405827
6    0.339547
Name: sils, dtype: float64

#### cl:  6
cl
0    0.287654
1    0.369464
2    0.311010
3    0.324315
4    0.352082
5    0.391504
6    0.339547
7    0.300435
Name: sils, dtype: float64

#### cl:  7
cl
0    0.282391
1    0.373517
2    0.311010
3    0.324315
4    0.352082
5    0.405192
6    0.339547
7    0.306758
8    0.160993
Name: sils, dtype: float64

