In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = pd.read_csv('1.clustering/titanic.csv')

target = data['Survived']
data = data.drop(['PassengerId', 'Survived'], axis=1)

In [2]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
categorical = [
    'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'
]

data['Age'] = pd.DataFrame(MinMaxScaler().fit_transform(data['Age'].values.reshape(-1,1)))
data['Fare'] = pd.DataFrame(StandardScaler().fit_transform(data['Fare'].values.reshape(-1,1)))

lbe = LabelEncoder()
data['Sex'] = lbe.fit_transform(data['Sex'])
sex = lbe.classes_
data['Embarked'] = lbe.fit_transform(data['Embarked'])
emb = lbe.classes_

# for c in categorical:
#     data = pd.concat([data, pd.get_dummies(data[c], prefix=c)], axis=1)
#     data = data.drop(c, axis=1)

train_X, test_X, train_y, test_y = train_test_split(data, target, test_size=0.3, random_state=0, shuffle=True)
    

In [3]:
from sklearn.svm import SVC

svm = SVC(kernel='linear').fit(train_X, train_y) # C, gamma parameter 있음

In [4]:
svm.coef_

array([[-0.04598578, -2.02957877, -0.41382966, -0.1487732 , -0.03379077,
         0.20314613, -0.03075195]])

In [5]:
accuracy_score(test_y, svm.predict(test_X))

0.7663551401869159

In [7]:
ans = train_y.replace(0, -1).values

In [8]:
def dist(a):
    res = np.sqrt(a @ a)
    return res

In [ ]:
d = []
for c in train_X.columns:
    tar = train_X[c].values
    s = 0
    for i in range(len(tar)):
        s += max(0, 1-ans[i]*tar[i]) * (-ans[i]*tar[i])
    d.append(s/len(tar))

In [ ]:
d

In [21]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a+b

a + 3

array([4, 5, 6])

In [38]:
dist(np.array([3,4]))

5.0

In [59]:
lamda = 1e-6
C = 1
w = np.array([-0.045, -2.029, -0.413, -0.148, -0.033, 0.203, -0.030])
for _ in range(100):
    di = dist(w)
    for i in range(len(train_X)):
        if ans[i] * (w@ train_X.values[i]) < 0:
            
            diff = max(0, ans[i])
        

6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
149
150
152
154
155
158
163
165
167
169
170
172
173
177
181
184
189
196
198
199
203
204
206
207
208
209
213
215
216
217
224
228
231
234
235
236
238
243
244
247
249
252
253
254
256
258
265
266
268
270
271
273
274
284
285
287
288
289
292
293
303
304
307
308
309
310
312
317
319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428
433
438
439
443
445
446
455
456
459
465
468
469
472
477
480
483
484
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
149
150
152
154
155
158
163
165
167
169
170
172
173
177
181
184
189
196
198
199
203
204
206
207
20

456
459
465
468
469
472
477
480
483
484
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
149
150
152
154
155
158
163
165
167
169
170
172
173
177
181
184
189
196
198
199
203
204
206
207
208
209
213
215
216
217
224
228
231
234
235
236
238
243
244
247
249
252
253
254
256
258
265
266
268
270
271
273
274
284
285
287
288
289
292
293
303
304
307
308
310
312
317
319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428
433
438
439
443
445
446
455
456
459
465
468
469
472
477
480
483
484
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
149
150
152
154
155
158
163
165
167
16

319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428
433
438
439
443
445
446
455
456
459
465
468
469
472
477
480
483
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
149
150
152
154
155
158
163
165
167
169
170
172
173
177
181
184
189
196
198
199
203
204
206
207
208
209
213
215
216
217
224
228
231
234
235
236
238
243
244
247
249
252
253
254
256
258
265
266
268
270
271
273
274
284
285
287
288
289
292
293
303
304
307
308
310
312
317
319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428
433
438
439
443
445
446
455
456
459
465
468
469
472
477
480
483
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60

217
224
228
231
234
235
236
238
243
244
247
249
252
253
254
256
258
265
266
268
270
271
273
274
284
285
287
288
289
292
293
303
304
307
308
310
312
317
319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428
433
438
439
443
445
446
455
456
459
465
468
469
472
477
480
483
486
487
490
491
492
497
6
7
9
21
25
29
32
37
41
44
45
46
47
48
50
51
52
55
57
58
60
64
67
70
72
73
79
83
85
91
93
97
101
105
107
109
111
112
113
115
116
120
122
123
124
125
126
128
131
132
134
135
139
142
144
145
147
150
152
154
155
158
163
165
167
169
170
172
173
177
181
184
189
196
198
199
203
204
206
207
208
209
213
215
216
217
224
228
231
234
235
236
238
243
244
247
249
252
253
254
256
258
265
266
268
270
271
273
274
284
285
287
288
289
292
293
303
304
307
308
310
312
317
319
325
326
327
330
333
334
335
337
340
341
346
351
355
356
361
363
364
365
366
376
379
387
390
391
392
394
399
403
404
406
411
413
418
422
423
424
428

KeyboardInterrupt: 

In [53]:
w

array([-0.00892617, -1.98599825, -0.39941675, -0.13692952, -0.02242439,
        0.2013038 , -0.00331403])

In [54]:
svm.coef_

array([[-0.04598578, -2.02957877, -0.41382966, -0.1487732 , -0.03379077,
         0.20314613, -0.03075195]])

In [62]:
svm.coef_ @ train_X.values[7]

array([-2.55797201])

In [63]:
ans[7]

1

In [ ]:
l = 1e-4
C = 1
w = np.array([-0.2,  2.00, -0.01, -0.22, -0.099,
         0.0032,  0.036])
for _ in range(100):
    a = list(map(lambda x: x*(1-l*C), w))
    b = list(map(lambda x: x*l, d))
    for j in range(len(w)):
        w[j] = a[j]+b[j]
    print(w[0])

In [ ]:
new

In [ ]:
np.ones(7) * l

In [ ]:
(np.ones(7) * (1-l*C))

In [ ]:
w

In [ ]:
w @ (np.ones(7) * (1-l*C))

In [ ]:
w = [0 for _ in range(7)]

In [11]:
ans

array([-1, -1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1,
       -1, -1, -1,  1, -1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1,  1,
        1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1,
        1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,
        1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1, -1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1,  1,
       -1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1,
       -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,
        1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1, -1,
       -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
        1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,
       -1, -1, -1,  1, -1