In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings(action='ignore')

d = load_boston()

std = StandardScaler()
data = pd.DataFrame(std.fit_transform(d.data), columns=d.feature_names)
target = std.fit_transform(d.target.reshape(-1,1))
dd = data.iloc[:,0:3]

In [157]:
from keras import models, layers

input_layer = layers.Input(shape=(data.shape[1],))

layer1 = layers.Dense(32, activation='relu')(input_layer)
layer2 = layers.Dense(16, activation='relu')(layer1)

out_layer = layers.Dense(1, activation='linear')(layer2) ## 분류는 마지막 층에 activation이 sigmoid였지만 회귀에서는 설정하지 않는다(linear)

model = models.Model(input_layer, out_layer)

In [158]:
model.compile(optimizer='adam',
             loss='mse',
             metrics=['mse'])

In [159]:
model.fit(data, target, epochs=50)

Epoch 1/50
506/506 [==============================] - 0s 627us/step - loss: 0.9531 - mse: 0.9531
Epoch 2/50
506/506 [==============================] - 0s 149us/step - loss: 0.6236 - mse: 0.6236
Epoch 3/50
506/506 [==============================] - 0s 222us/step - loss: 0.4453 - mse: 0.4453
Epoch 4/50
506/506 [==============================] - 0s 247us/step - loss: 0.3274 - mse: 0.3274
Epoch 5/50
506/506 [==============================] - 0s 254us/step - loss: 0.2594 - mse: 0.2594
Epoch 6/50
506/506 [==============================] - 0s 244us/step - loss: 0.2230 - mse: 0.2230
Epoch 7/50
506/506 [==============================] - 0s 258us/step - loss: 0.2008 - mse: 0.2008
Epoch 8/50
506/506 [==============================] - 0s 246us/step - loss: 0.1864 - mse: 0.1864
Epoch 9/50
506/506 [==============================] - 0s 248us/step - loss: 0.1770 - mse: 0.1770
Epoch 10/50
506/506 [==============================] - 0s 262us/step - loss: 0.1672 - mse: 0.1672
Epoch 11/50
506/506 [========

In [16]:
len(model.layers[1].get_weights()[0])

13

In [15]:
len(data.columns)

13

In [17]:
def relu(a):
    return max(0, a)

In [85]:
ls1 = model.layers[1].get_weights()

In [86]:
d1 = data.iloc[0,:]

In [115]:
res = []

for i in range(len(ls1[0][0])):
    temp = 0
    for j in range(13):
        temp += ls1[0][j][i] * d1[j]
#     temp = relu(temp)
    temp += ls1[0][1][i]
    res.append(temp)

In [150]:
np.array(list(map(relu, d1.values @ l[0] + l[1]))) @ l[2] + l[3]

array([0.53393573])

In [136]:
np.array(list(map(relu, d1.values @ l[0] + l[1])))

array([0.06076025, 0.63698067, 0.34921543, 0.14380016, 1.19569301,
       0.30774345, 0.        , 0.        , 0.21937795, 0.17100938,
       0.        , 0.        , 0.47213362, 0.        , 0.        ,
       0.4706104 , 0.75636843, 1.2552416 , 0.55731434, 0.48246728,
       0.        , 0.48963836, 0.        , 0.        , 0.        ,
       0.03627886, 0.66644765, 0.41316772, 0.97149563, 0.        ,
       0.468878  , 0.        ])

In [152]:
model.predict(data)

array([[ 5.33935845e-01],
       [ 1.02831118e-01],
       [ 1.05041265e+00],
       [ 1.02527821e+00],
       [ 9.92448688e-01],
       [ 3.18605304e-01],
       [-2.98256725e-01],
       [-3.89213890e-01],
       [-7.68468857e-01],
       [-4.70633835e-01],
       [-3.05568516e-01],
       [-3.97294730e-01],
       [-3.69296104e-01],
       [-4.15025830e-01],
       [-6.17720962e-01],
       [-3.75638992e-01],
       [-3.25272828e-02],
       [-6.87347054e-01],
       [-3.71438593e-01],
       [-5.46455681e-01],
       [-9.05557036e-01],
       [-7.16567338e-01],
       [-7.17734218e-01],
       [-8.71166229e-01],
       [-7.88458347e-01],
       [-7.90755093e-01],
       [-7.90355086e-01],
       [-7.84169197e-01],
       [-5.50705850e-01],
       [-3.27253193e-01],
       [-8.99262667e-01],
       [-7.54126549e-01],
       [-6.33898795e-01],
       [-8.40342999e-01],
       [-8.03664088e-01],
       [-1.85981572e-01],
       [-2.26843923e-01],
       [-3.68031263e-02],
       [ 1.1

In [107]:
ls1[1] @ res

-0.017624723339644627

In [121]:
for l in model.layers:
    print(l.get_weights())

[]
[array([[-0.15910591, -0.13329878, -0.16317365,  0.22305135, -0.2294827 ,
         0.27897084,  0.02517909,  0.15517353,  0.21889347,  0.04299084,
        -0.36934593,  0.12737064, -0.11454207,  0.29121807,  0.17554778,
        -0.39159346, -0.1349283 ,  0.28123975, -0.22132327,  0.40667313,
         0.39287797, -0.12081485,  0.15532216,  0.00067196,  0.20001534,
         0.2616138 ,  0.06307539, -0.11103588,  0.07741212,  0.2713978 ,
        -0.15571558,  0.26567462],
       [-0.15558895, -0.18242909,  0.3638434 ,  0.42502353,  0.04803775,
        -0.23196673, -0.12497982, -0.30697453,  0.18402313,  0.0628478 ,
         0.00584842, -0.3216632 ,  0.06199934, -0.19639583,  0.01461156,
        -0.15407747,  0.23055498, -0.2060447 ,  0.13533893,  0.10457414,
        -0.4157355 ,  0.2266804 , -0.29474458, -0.1952739 ,  0.13014348,
         0.1668489 , -0.26847845,  0.36726433,  0.25705078, -0.24060471,
        -0.06364115, -0.15471725],
       [ 0.12857936, -0.15710518,  0.33029422, -0.

In [127]:
l = model.get_weights()

In [155]:
k = model.layers[1]

In [178]:
from keras import models, layers

input_layer = layers.Input(shape=(data.shape[1],))

layer1 = layers.Dense(32, activation='relu')(input_layer)

out_layer = layers.Dense(1, activation='linear')(layer1) ## 분류는 마지막 층에 activation이 sigmoid였지만 회귀에서는 설정하지 않는다(linear)

m = models.Model(input_layer, out_layer)


In [179]:
m.layers[1].set_weights(model.layers[1].get_weights())

In [177]:
m.predict(data)

array([[-0.55357647],
       [-0.37509614],
       [-0.80215526],
       [-0.84425724],
       [-0.8016189 ],
       [-0.5307802 ],
       [-0.3255147 ],
       [-0.2706234 ],
       [-0.5866089 ],
       [-0.20967552],
       [-0.27869636],
       [-0.29016355],
       [-0.37920365],
       [-0.23638007],
       [-0.28617644],
       [-0.18524693],
       [-0.35047162],
       [-0.39378557],
       [-0.04263767],
       [-0.23483607],
       [-0.6489237 ],
       [-0.42408246],
       [-0.631002  ],
       [-0.66668034],
       [-0.5262756 ],
       [-0.40967733],
       [-0.45123285],
       [-0.40978166],
       [-0.47062755],
       [-0.47550628],
       [-0.6381248 ],
       [-0.44926572],
       [-0.580556  ],
       [-0.5461509 ],
       [-0.54603875],
       [-0.2129415 ],
       [-0.18117179],
       [-0.31522605],
       [-0.43485257],
       [-0.92272663],
       [-1.1518912 ],
       [-1.0648046 ],
       [-0.67647743],
       [-0.6790536 ],
       [-0.3168606 ],
       [-0

In [180]:
m.predict(data)

array([[ 0.52036417],
       [ 0.54574627],
       [ 0.28126073],
       [ 0.4819435 ],
       [ 0.48885235],
       [ 0.63193095],
       [ 0.4420495 ],
       [ 0.4369373 ],
       [ 0.6316395 ],
       [ 0.3504258 ],
       [ 0.47694364],
       [ 0.3892518 ],
       [ 0.57710457],
       [ 0.5350986 ],
       [ 0.43419176],
       [ 0.5348546 ],
       [ 0.4677175 ],
       [ 0.32988822],
       [ 0.2347565 ],
       [ 0.46106392],
       [ 0.13281995],
       [ 0.3599893 ],
       [ 0.18214379],
       [ 0.23785418],
       [ 0.33564198],
       [ 0.1272039 ],
       [ 0.3653393 ],
       [ 0.10150617],
       [ 0.2592425 ],
       [ 0.13312712],
       [ 0.15254846],
       [ 0.28894967],
       [-0.05816157],
       [ 0.13527393],
       [-0.07299683],
       [ 0.513118  ],
       [ 0.43180126],
       [ 0.599903  ],
       [ 0.53341484],
       [ 1.144826  ],
       [ 1.0134898 ],
       [ 0.5250338 ],
       [ 0.603473  ],
       [ 0.615078  ],
       [ 0.52633864],
       [ 0

In [185]:
m.layers[3].get_weights()

IndexError: list index out of range